### ISSUE TITLE
Python Implementation

### ISSUE THREAD

**Issue by regmeg** [SaxoBank/openapi-clientlib-js#109]
Hi Guys,

Thanks for the JS API implementation you provide.

I know it's not an issue, rather a comment, but I dont think there's anywhere else I can raise this with saxo as a dev.

What I wanted to ask is, why a JS implementation and not a Python implementation? Is this a fork from what you use at the backend and it's in JS? 

JS seems a rather inconvenient choice for algo traders, since I rarely see it used anywhere else in the domain. Say I need to do some data processing, machine learning, integrate with 3rd party backtested/live trading platform, most tools available for this out there are python if we talk higher-level language. JS API library requires extra, hacky integration work/interfaces. 

I would love to have an API library from you, particularly for live streaming prices and trading events. I struggle quite a bit to make a stable socket with you in python at the moment, if there was a stable library from you provided for the API in python it would be so great.

Again sorry for not raising an issue, but rather for commenting. 

Thank you.

**Comment by lukeapage** [comment]
Hi, we do use this library internally for our front end trading applications, which is why it is JavaScript. I will see if I can find someone to answer you from the open api product team.

**Comment by gidven** [comment]
Hi regmeg,

Feite Brekeveld created a Python wrapper for our OpenAPI - [check it out here](https://github.com/hootnot/saxo_openapi). It's not an official Saxo implementation but we did work closely on this and it's of course entirely open source. [Here's an example](https://github.com/hootnot/saxo_openapi/blob/c5b75274df0c6d30b61987d1e35b59fc6055d6f4/docs/examples/stream_proc.rst) of his using websockets in Python.

I am currently working on some standalone streaming samples that should go out on this repo in due course. Send me a private message if you want to see what I have so far.

/Gid
Saxo OpenAPI Team
