### ISSUE TITLE
Link to documentation seems outdated

### ISSUE THREAD

**Issue by jbmusso** [SaxoBank/openapi-clientlib-js#179]
The link to doclets.io is broken, currently https://doclets.io/SaxoBank/openapi-clientlib-js/master

Unsure if this is expected or not. Could you please point to an updated link to the documentatin, if any? Thanks

**Comment by lukeapage** [comment]
It seems docklets.io is now defunct.

The documentation for this library is all jsdoc and markdown. Until we replace the documentation generator I suggest you use a combination of the open api portal and viewing the source - sorry about that.

**Comment by jbmusso** [comment]
Thanks for the quick reply, Luke!

**Comment by jbmusso** [comment]
As a quick workaround, the following command will build the doc in the `./out` folder and serve it via a local server listening on port `5000`:

```bash
npx jsdoc src && npx serve out
```

Browing to `http://localhost:5000/` will show the content.

While thinking about it, there might be a way to automatically publish this to GitHub pages via GitHub actions.
