### ISSUE TITLE
Purpose of files in libs directory

### ISSUE THREAD

**Issue by michax** [SaxoBank/openapi-clientlib-js#3]
What's a purpose of files found in libs directory? Most of them aren't used directly in this project. 
Some of them are external dependencies(signalR, jQuery), however documentations suggests to configure external dependencies manually using direct sources.

**Comment by lukeapage** [comment]
We can get rid of the directory, its a legacy folder related to how we used to use/develop the library - I'm happy to reference files through npm/node_modules. PR's welcome!
