### ISSUE TITLE
Support for NodeJS

### ISSUE THREAD

**Issue by Froelund** [SaxoBank/openapi-clientlib-js#57]
Hi!

I'm currently trying to consume the openapi from NodeJS. 

My on this, is that there is a dependency to the browser, and as far as I can see, it is solely caused by a dependency to SignalR library.

I have no experience with SignalR, and I haven't read too much up on it, but would it be possible to abstract the signalR-connection and add the ability to provide "your own" implementation when constructing `Streaming`?

I have an implementation in mind:

I will change the signature of the constructor to this:
```
function Streaming(transport, baseUrl, authProvider, options, signalClientProvider) {}
```

Then in the init function I will create the connection using the signalClientProvider instead of `$.connection()`.
```
const connection = this.signalClientProvider(this.connectionUrl);
```

`signalClientProvider` will also be responsible for providing connection states:
```
/**
 * maps from the signalR connection state to the ConnectionState Enum
 */
function mapConnectionState(state) {
    let connectionState;
    switch (state) {
        case this.signalClientProvider.states.connecting: connectionState = this.CONNECTION_STATE_CONNECTING; break;

        case this.signalClientProvider.states.connected: connectionState = this.CONNECTION_STATE_CONNECTED; break;

        case this.signalClientProvider.states.disconnected: connectionState = this.CONNECTION_STATE_DISCONNECTED; break;

        case this.signalClientProvider.states.reconnecting: connectionState = this.CONNECTION_STATE_RECONNECTING; break;

        default:
            log.warn(LOG_AREA, 'unrecognised state', state);
            break;
    }

    return connectionState;
}
```

Wouldn't this be all that is needed to be able to use the client outside the browser?

**Comment by lukeapage** [comment]
Sorry @Froelund I missed the issue.

I'm happy with allowing signal r to be injected so that a non browser version could be used.
