### ISSUE TITLE
Why do you need visual studio project files

### ISSUE THREAD

**Issue by michax** [SaxoBank/openapi-clientlib-js#6]
Why do you need visual studio project files? And if they are needed i think they should have different names then SharedJS.

Files in question:
* SharedJS.csproj, 
* SharedJS.sln

**Comment by graffen** [comment]
The VS files are mostly there for historic reasons because the library was originally developed in VS. Now, with VS2017 being able to "Open Folder" and not really requiring these files anymore, I think we can safely remove them. Most will probably work on this lib in something other than VS anyway.
