### ISSUE TITLE
Question about api limits

### ISSUE THREAD

**Issue by LambdaMan2K** [SaxoBank/openapi-clientlib-js#603]
hi, can someone please tell me if the open api access of 10k daily limit requests.  is the request count incremented for every like info price subscription response message or just for the sub/unsub request . I know it is not a request but a stream of responses, I just wonder if it counts as activity  or not? and if hopefully not then can I then set the refresh rate for the sub to be 500 mils ? 
thank you

**Comment by lukeapage** [comment]
Sorry, I missed this issue.

You can reach out to the open api development support. But the limit is afaik per minute for requests and for subscriptions, the limit is the number running in parallel.
