### ISSUE TITLE
Publishing to NPM

### ISSUE THREAD

**Issue by jutaz** [SaxoBank/openapi-clientlib-js#641]
Thoughts on publishing this to NPM as a package? I'd like to use this, but cloning doesn't seem like the most efficient (or safe, from versioning standpoint) way to acquire this package.

**Comment by michax** [comment]
Hi, It's available in npm and up to date with latest master.
https://www.npmjs.com/package/openapi-clientlib

We will update wiki to include information about published npm.

**Comment by michax** [comment]
Readme updated.

**Comment by jutaz** [comment]
This is great, thank you!
