### ISSUE TITLE
Space between number and percentage sign

### ISSUE THREAD

**Issue by stanleyxu2005** [SaxoBank/openapi-clientlib-js#96]
I admit that "10.2 %" and "10.2%" are both correct at some degree. But I'd like to ask, whether the project will consider switch "10.2 %" to "10.2%". To be honest, the second notation is more frequently seen in life.

Here are some interesting discussion https://english.stackexchange.com/questions/3281/should-there-be-a-space-before-a-percent-sign

> When the symbol % is used, there should be no space. When the "percent" word is used, there should be space.
> 
> Examples from the Chicago Manual of Style Online:
>
>> Fewer than 3 percent of the employees used public transportation.
>> With 90–95 percent of the work complete, we can relax.
>> A 75 percent likelihood of winning is worth the effort.
>> Her five-year certificate of deposit carries an interest rate of 5.9 percent.
>> Only 20% of the ants were observed to react to the stimulus.
>> The treatment resulted in a 20%–25% increase in reports of night blindness.
> 
> The manual explicitly advices the following:
>> Note also that no space appears between the numeral and the symbol %.

**Comment by lukeapage** [comment]
I don’t have a strong opinion. I agree without space seems more natural as a British person.. within saxotrader I think readability is the most important. I’d suggest we run it past a designer/ product owner.

**Comment by lukeapage** [comment]
Most of the platform doesn't have spaces right now, so I've merged this. Sorry for the delay.
